"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const dmv_1 = require("./dmv");
// dem_r_buf();
// test_path_finder();
// console.log("contains 25: ", contains_node(25));
// console.log("contains 26: ", contains_node(26));
// console.log("is valid tree: ", validate_b_tree());
// console.log("is invalid tree: ", validate_invalid_tree());
// const b_tree = new BTree();
// b_tree.create_valid_b_tree();
//const is_found = test_b_search();
//console.log("is the number found", is_found);
(0, dmv_1.example)();
